leftnav:
- identifier: 4d869bd3-39d1-9104-3d20-4c9ff2f9fa05
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 736b7208-d727-f498-9a0e-2d126142925d
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 5ee35bb0-08b6-f8ad-0f29-9d89e0405487
  name: Assignments
  pageRef: /pages/assignments
  weight: 30
- identifier: 0bcf7875-aeca-ce03-9079-b5bdd8cf84ca
  name: Projects
  pageRef: /pages/projects/
  weight: 40
- identifier: 8e629f2c-820f-14fd-eee5-a9442b2eaada
  name: References
  pageRef: /pages/references
  weight: 50
